import type { ConceptMeta } from '../schema'

export const agents: ConceptMeta[] = [
  {
    id: 'agent-loop',
    title: 'El bucle agéntico (ReAct)',
    short: 'Pensar, actuar, observar, repetir: un LLM que decide qué herramienta usar hasta completar la tarea.',
    layer: 'agents',
    kind: 'pattern',
    level: 1,
    tags: ['ReAct', 'bucle', 'observación', 'autonomía'],
    prerequisites: ['tool-calling'],
    relations: [{ to: 'reasoning-models', type: 'uses' }],
  },
  {
    id: 'workflow-patterns',
    title: 'Workflows vs agentes',
    short: 'Chaining, routing, paralelización, orchestrator-workers, evaluator-optimizer: empieza por lo más simple.',
    layer: 'agents',
    kind: 'pattern',
    level: 2,
    tags: ['prompt chaining', 'routing', 'orchestrator-workers', 'evaluator-optimizer'],
    prerequisites: ['agent-loop'],
    relations: [
      {
        to: 'agent-loop',
        type: 'alternative',
        note: 'workflow: camino predefinido; agente: el modelo decide',
      },
    ],
  },
  {
    id: 'stateful-graphs',
    title: 'Grafos con estado',
    short: 'Orquestar agentes como grafos con estado, checkpoints, bucles e interrupciones humanas (p. ej. LangGraph).',
    layer: 'agents',
    kind: 'pattern',
    level: 2,
    tags: ['LangGraph', 'checkpoints', 'human-in-the-loop', 'time-travel'],
    prerequisites: ['workflow-patterns'],
    relations: [
      { to: 'agent-loop', type: 'implements' },
      { to: 'agent-memory', type: 'uses' },
    ],
    labId: 'agent-graph',
  },
  {
    id: 'multi-agent',
    title: 'Sistemas multi-agente',
    short: 'Varios agentes especializados que colaboran: más capacidad, más coste y más formas de fallar.',
    layer: 'agents',
    kind: 'pattern',
    level: 3,
    tags: ['supervisor', 'subagentes', 'handoffs'],
    prerequisites: ['stateful-graphs'],
    relations: [{ to: 'agent-loop', type: 'uses' }],
  },
  {
    id: 'agent-frameworks',
    title: 'Panorama de frameworks',
    short: 'LangGraph, Claude Agent SDK, OpenAI Agents SDK, Pydantic AI, CrewAI…: qué abstrae cada uno.',
    layer: 'agents',
    kind: 'tool',
    level: 2,
    tags: ['LangGraph', 'Agent SDK', 'Pydantic AI', 'CrewAI', 'Mastra'],
    prerequisites: ['stateful-graphs'],
    relations: [
      { to: 'stateful-graphs', type: 'implements' },
      { to: 'mcp', type: 'uses' },
    ],
  },
  {
    id: 'coding-agents',
    title: 'Agentes de código',
    short: 'Claude Code, Codex, Cursor…: agentes que leen tu repo, ejecutan comandos y editan código.',
    layer: 'agents',
    kind: 'tool',
    level: 2,
    tags: ['Claude Code', 'Codex', 'Cursor', 'terminal'],
    prerequisites: ['agent-loop', 'code-sandboxes'],
    relations: [
      { to: 'mcp', type: 'uses' },
      { to: 'agent-loop', type: 'implements' },
    ],
  },
]
