import type { ConceptMeta } from '../schema'

export const fundamentals: ConceptMeta[] = [
  {
    id: 'tokenization',
    title: 'Tokenización',
    short: 'El texto se trocea en tokens (sub-palabras) antes de entrar al modelo: la unidad de coste, de contexto y de error.',
    layer: 'fundamentals',
    kind: 'concept',
    level: 1,
    tags: ['BPE', 'tokens', 'vocabulario', 'tiktoken'],
    prerequisites: [],
    relations: [{ to: 'embeddings', type: 'enables', note: 'cada token id indexa un vector' }],
    labId: 'tokenizer',
  },
  {
    id: 'embeddings',
    title: 'Embeddings',
    short: 'Vectores densos donde la distancia geométrica aproxima la similitud de significado.',
    layer: 'fundamentals',
    kind: 'concept',
    level: 1,
    tags: ['vectores', 'similitud coseno', 'espacio latente'],
    prerequisites: ['tokenization'],
    relations: [{ to: 'attention', type: 'enables', note: 'la atención opera sobre estos vectores' }],
    labId: 'embeddings',
  },
  {
    id: 'attention',
    title: 'Transformer y self-attention',
    short: 'Cada token mira a los anteriores y decide cuánto le importa cada uno: el mecanismo central del transformer.',
    layer: 'fundamentals',
    kind: 'concept',
    level: 2,
    tags: ['transformer', 'Q K V', 'multi-head', 'RoPE', 'GQA'],
    prerequisites: ['embeddings'],
    relations: [{ to: 'context-window', type: 'enables' }],
  },
  {
    id: 'next-token',
    title: 'Predicción del siguiente token',
    short: 'Un LLM solo hace una cosa: dada una secuencia, produce una distribución de probabilidad sobre el siguiente token.',
    layer: 'fundamentals',
    kind: 'concept',
    level: 1,
    tags: ['logits', 'softmax', 'autoregresivo', 'vocabulario'],
    prerequisites: ['attention', 'tokenization'],
    relations: [{ to: 'sampling', type: 'enables' }],
  },
  {
    id: 'sampling',
    title: 'Sampling: temperature, top-k, top-p',
    short: 'Cómo se elige un token de la distribución: la temperatura y los filtros deciden entre creatividad y fiabilidad.',
    layer: 'fundamentals',
    kind: 'technique',
    level: 1,
    tags: ['temperature', 'top-p', 'nucleus', 'min-p', 'greedy'],
    prerequisites: ['next-token'],
    relations: [],
    labId: 'sampling',
  },
  {
    id: 'context-window',
    title: 'Ventana de contexto y KV cache',
    short: 'Cuántos tokens "ve" el modelo a la vez, por qué cuesta memoria y cómo el KV cache evita recalcular.',
    layer: 'fundamentals',
    kind: 'concept',
    level: 2,
    tags: ['contexto', 'KV cache', 'prefill', 'decode', 'lost in the middle'],
    prerequisites: ['attention', 'tokenization'],
    relations: [],
    labId: 'context',
  },
  {
    id: 'training',
    title: 'Entrenamiento: pre-training → SFT → RLHF',
    short: 'De predecir internet a seguir instrucciones: las fases que convierten un modelo base en un asistente.',
    layer: 'fundamentals',
    kind: 'concept',
    level: 2,
    tags: ['pre-training', 'SFT', 'RLHF', 'DPO', 'modelo base'],
    prerequisites: ['next-token'],
    relations: [
      { to: 'fine-tuning', type: 'enables' },
      { to: 'reasoning-models', type: 'enables', note: 'RL sobre tareas verificables' },
    ],
  },
  {
    id: 'reasoning-models',
    title: 'Modelos de razonamiento',
    short: 'Modelos entrenados para "pensar" antes de responder: más cómputo en inferencia a cambio de más precisión.',
    layer: 'fundamentals',
    kind: 'concept',
    level: 2,
    tags: ['test-time compute', 'chain of thought', 'extended thinking', 'RL'],
    prerequisites: ['training', 'sampling'],
    relations: [{ to: 'agent-loop', type: 'enables', note: 'planifican y corrigen mejor' }],
  },
  {
    id: 'mixture-of-experts',
    title: 'Mixture of Experts (MoE)',
    short: 'Muchos parámetros, pocos activos por token: un router envía cada token a unos pocos "expertos".',
    layer: 'fundamentals',
    kind: 'concept',
    level: 3,
    tags: ['MoE', 'router', 'parámetros activos', 'sparse'],
    prerequisites: ['attention'],
    relations: [
      { to: 'attention', type: 'part-of', note: 'sustituye la capa FFN del bloque transformer' },
    ],
  },
]
