import type { ConceptMeta } from '../schema'

export const inference: ConceptMeta[] = [
  {
    id: 'quantization',
    title: 'Cuantización',
    short: 'Guardar los pesos con menos bits (8, 4…) para que el modelo quepa en tu GPU a cambio de algo de precisión.',
    layer: 'inference',
    kind: 'technique',
    level: 2,
    tags: ['int8', 'int4', 'Q4_K_M', 'AWQ', 'GPTQ', 'VRAM'],
    prerequisites: ['next-token'],
    relations: [
      { to: 'weight-formats', type: 'uses' },
      { to: 'local-runtimes', type: 'enables' },
    ],
    labId: 'vram',
  },
  {
    id: 'weight-formats',
    title: 'Formatos de pesos',
    short: 'safetensors, GGUF, AWQ/GPTQ, MLX: el formato determina qué runtime puede cargar el modelo.',
    layer: 'inference',
    kind: 'concept',
    level: 2,
    tags: ['safetensors', 'GGUF', 'MLX', 'ONNX'],
    prerequisites: ['quantization'],
    relations: [{ to: 'local-runtimes', type: 'enables' }],
  },
  {
    id: 'local-runtimes',
    title: 'Runtimes locales',
    short: 'llama.cpp, Ollama y LM Studio: ejecutar modelos en tu propio hardware.',
    layer: 'inference',
    kind: 'tool',
    level: 1,
    tags: ['llama.cpp', 'Ollama', 'LM Studio', 'CPU', 'GPU'],
    prerequisites: ['quantization', 'weight-formats'],
    relations: [
      { to: 'serving-engines', type: 'alternative', note: 'un usuario vs cientos concurrentes' },
      { to: 'llm-apis', type: 'implements', note: 'endpoints compatibles con OpenAI' },
    ],
  },
  {
    id: 'serving-engines',
    title: 'Serving en producción',
    short: 'vLLM, SGLang, TensorRT-LLM: servir a muchos usuarios con continuous batching y PagedAttention.',
    layer: 'inference',
    kind: 'tool',
    level: 3,
    tags: ['vLLM', 'SGLang', 'PagedAttention', 'continuous batching'],
    prerequisites: ['context-window', 'local-runtimes'],
    relations: [
      { to: 'inference-optimizations', type: 'uses' },
      { to: 'llm-apis', type: 'implements' },
    ],
  },
  {
    id: 'inference-optimizations',
    title: 'Optimizaciones de inferencia',
    short: 'Speculative decoding, prompt caching y FlashAttention: más tokens por segundo con el mismo hardware.',
    layer: 'inference',
    kind: 'technique',
    level: 3,
    tags: ['speculative decoding', 'prompt caching', 'FlashAttention'],
    prerequisites: ['context-window', 'next-token'],
    relations: [{ to: 'latency-cost-metrics', type: 'improves' }],
  },
  {
    id: 'latency-cost-metrics',
    title: 'Latencia y coste',
    short: 'TTFT, tokens/s, throughput y precio por millón de tokens: las métricas que deciden la experiencia y la factura.',
    layer: 'inference',
    kind: 'concept',
    level: 1,
    tags: ['TTFT', 'TPOT', 'throughput', 'precio'],
    prerequisites: ['tokenization'],
    relations: [],
  },
  {
    id: 'llm-apis',
    title: 'APIs de LLM',
    short: 'Mensajes, roles, streaming y parámetros: el contrato con el que tu código habla con cualquier modelo.',
    layer: 'inference',
    kind: 'concept',
    level: 1,
    tags: ['Messages API', 'Chat Completions', 'streaming', 'SSE'],
    prerequisites: ['tokenization', 'sampling'],
    relations: [
      { to: 'tool-calling', type: 'enables' },
      { to: 'structured-outputs', type: 'enables' },
    ],
  },
]
