import type { ConceptMeta } from '../schema'

export const knowledge: ConceptMeta[] = [
  {
    id: 'rag',
    title: 'Arquitectura RAG',
    short: 'Recuperar documentos relevantes e inyectarlos en el contexto para que el modelo responda con tus datos.',
    layer: 'knowledge',
    kind: 'pattern',
    level: 1,
    tags: ['retrieval', 'grounding', 'contexto'],
    prerequisites: ['embeddings', 'context-window'],
    relations: [
      { to: 'context-window', type: 'uses' },
      { to: 'vector-databases', type: 'uses' },
    ],
    labId: 'rag',
  },
  {
    id: 'chunking',
    title: 'Chunking',
    short: 'Cómo trocear documentos para indexarlos: tamaño, solape y límites semánticos cambian lo que se recupera.',
    layer: 'knowledge',
    kind: 'technique',
    level: 1,
    tags: ['chunk size', 'overlap', 'semantic chunking'],
    prerequisites: ['tokenization'],
    relations: [{ to: 'rag', type: 'part-of' }],
    labId: 'chunking',
  },
  {
    id: 'embedding-models',
    title: 'Modelos de embedding',
    short: 'Elegir el modelo que convierte texto en vectores: idioma, dimensiones, contexto y coste.',
    layer: 'knowledge',
    kind: 'tool',
    level: 2,
    tags: ['MTEB', 'dimensiones', 'Matryoshka', 'multilingüe'],
    prerequisites: ['embeddings'],
    relations: [
      { to: 'embeddings', type: 'implements' },
      { to: 'rag', type: 'part-of' },
    ],
  },
  {
    id: 'ann-indexes',
    title: 'Índices ANN',
    short: 'HNSW, IVF, PQ: buscar vecinos aproximados en millones de vectores en milisegundos.',
    layer: 'knowledge',
    kind: 'technique',
    level: 3,
    tags: ['HNSW', 'IVF', 'PQ', 'recall'],
    prerequisites: ['embedding-models'],
    relations: [{ to: 'vector-databases', type: 'part-of' }],
  },
  {
    id: 'vector-databases',
    title: 'Bases de datos vectoriales',
    short: 'pgvector, Qdrant, Chroma, LanceDB…: almacenar vectores con metadatos, filtros y actualizaciones.',
    layer: 'knowledge',
    kind: 'tool',
    level: 2,
    tags: ['pgvector', 'Qdrant', 'Chroma', 'filtros'],
    prerequisites: ['ann-indexes'],
    relations: [{ to: 'agent-memory', type: 'enables' }],
  },
  {
    id: 'hybrid-search',
    title: 'Búsqueda híbrida',
    short: 'Combinar BM25 (palabras exactas) y vectores (significado) con fusión de rankings (RRF).',
    layer: 'knowledge',
    kind: 'technique',
    level: 2,
    tags: ['BM25', 'RRF', 'sparse', 'dense'],
    prerequisites: ['vector-databases'],
    relations: [{ to: 'rag', type: 'improves' }],
  },
  {
    id: 'reranking',
    title: 'Re-ranking',
    short: 'Un segundo modelo (cross-encoder) reordena los candidatos leyendo consulta y documento juntos.',
    layer: 'knowledge',
    kind: 'technique',
    level: 2,
    tags: ['cross-encoder', 'precisión', 'top-k'],
    prerequisites: ['rag'],
    relations: [{ to: 'rag', type: 'improves' }],
  },
  {
    id: 'advanced-rag',
    title: 'RAG avanzado',
    short: 'Query rewriting, HyDE, contextual retrieval, GraphRAG y agentic RAG: cuándo compensa cada uno.',
    layer: 'knowledge',
    kind: 'pattern',
    level: 3,
    tags: ['HyDE', 'GraphRAG', 'contextual retrieval', 'agentic RAG'],
    prerequisites: ['rag', 'hybrid-search', 'reranking'],
    relations: [
      { to: 'rag', type: 'improves' },
      { to: 'agent-loop', type: 'uses', note: 'agentic RAG' },
    ],
  },
  {
    id: 'agent-memory',
    title: 'Memoria de agentes',
    short: 'Memoria de trabajo, episódica y semántica: qué recordar, cuándo resumir y dónde guardarlo.',
    layer: 'knowledge',
    kind: 'pattern',
    level: 2,
    tags: ['memoria', 'resumen', 'perfil de usuario'],
    prerequisites: ['rag', 'context-window'],
    relations: [{ to: 'agent-loop', type: 'part-of' }],
  },
]
