import type { ConceptMeta } from '../schema'

export const models: ConceptMeta[] = [
  {
    id: 'open-vs-closed',
    title: 'Modelos cerrados vs open-weights',
    short: 'API propietaria o pesos descargables: control, coste, privacidad y licencias en juego.',
    layer: 'models',
    kind: 'concept',
    level: 1,
    tags: ['open weights', 'licencias', 'API', 'privacidad'],
    prerequisites: ['training'],
    relations: [
      { to: 'hugging-face', type: 'uses' },
      { to: 'local-runtimes', type: 'enables' },
    ],
  },
  {
    id: 'model-landscape',
    title: 'Panorama de modelos',
    short: 'Snapshot fechado de las familias de modelos relevantes y para qué destaca cada una.',
    layer: 'models',
    kind: 'concept',
    level: 1,
    tags: ['Claude', 'GPT', 'Gemini', 'Llama', 'Qwen', 'Mistral', 'DeepSeek'],
    prerequisites: ['open-vs-closed'],
    relations: [
      { to: 'reasoning-models', type: 'uses' },
      { to: 'multimodality', type: 'uses' },
      { to: 'mixture-of-experts', type: 'uses' },
    ],
  },
  {
    id: 'model-selection',
    title: 'Cómo elegir modelo',
    short: 'Capacidad, latencia, coste, contexto y licencia: elegir el modelo más pequeño que resuelve tu tarea.',
    layer: 'models',
    kind: 'technique',
    level: 2,
    tags: ['trade-offs', 'cascadas', 'routing', 'SLM'],
    prerequisites: ['model-landscape', 'benchmarks'],
    relations: [{ to: 'latency-cost-metrics', type: 'uses' }],
  },
  {
    id: 'hugging-face',
    title: 'Hugging Face Hub',
    short: 'El repositorio central de pesos, datasets, model cards y demos del ecosistema abierto.',
    layer: 'models',
    kind: 'tool',
    level: 1,
    tags: ['hub', 'model card', 'datasets', 'transformers'],
    prerequisites: [],
    relations: [{ to: 'weight-formats', type: 'uses' }],
  },
  {
    id: 'benchmarks',
    title: 'Benchmarks y sus límites',
    short: 'Qué miden MMLU, SWE-bench o las arenas, y por qué no sustituyen a evaluar tu propio caso.',
    layer: 'models',
    kind: 'concept',
    level: 2,
    tags: ['MMLU', 'SWE-bench', 'arena', 'contaminación', 'lm-eval-harness'],
    prerequisites: ['training'],
    relations: [
      { to: 'evals', type: 'alternative', note: 'benchmarks miden modelos; evals miden tu sistema' },
    ],
  },
  {
    id: 'multimodality',
    title: 'Multimodalidad',
    short: 'Imágenes, audio y documentos como tokens: cómo un modelo de lenguaje "ve" y "oye".',
    layer: 'models',
    kind: 'concept',
    level: 2,
    tags: ['visión', 'audio', 'VLM', 'patches'],
    prerequisites: ['embeddings', 'attention'],
    relations: [{ to: 'computer-use', type: 'enables' }],
  },
]
