import type { ConceptMeta } from '../schema'

export const production: ConceptMeta[] = [
  {
    id: 'evals',
    title: 'Evals',
    short: 'Tests para sistemas no deterministas: datasets, métricas y umbrales antes y después de desplegar.',
    layer: 'production',
    kind: 'technique',
    level: 1,
    tags: ['dataset', 'métricas', 'regresión', 'Ragas', 'promptfoo'],
    prerequisites: ['llm-apis'],
    relations: [
      { to: 'rag', type: 'evaluates' },
      { to: 'agent-loop', type: 'evaluates' },
    ],
    labId: 'evals',
  },
  {
    id: 'llm-as-judge',
    title: 'LLM-as-judge',
    short: 'Usar un modelo con una rúbrica para puntuar respuestas: escalable, útil y con sesgos conocidos.',
    layer: 'production',
    kind: 'technique',
    level: 2,
    tags: ['rúbrica', 'sesgos', 'pairwise'],
    prerequisites: ['evals'],
    relations: [{ to: 'evals', type: 'part-of' }],
  },
  {
    id: 'observability',
    title: 'Observabilidad y tracing',
    short: 'Trazas de cada llamada, herramienta y paso del agente para depurar, medir y mejorar.',
    layer: 'production',
    kind: 'technique',
    level: 2,
    tags: ['tracing', 'OpenTelemetry', 'Langfuse', 'LangSmith'],
    prerequisites: ['agent-loop'],
    relations: [{ to: 'evals', type: 'enables', note: 'las trazas reales alimentan los datasets' }],
  },
  {
    id: 'prompt-injection',
    title: 'Prompt injection',
    short: 'Instrucciones maliciosas escondidas en datos que el modelo lee: el riesgo nº 1 de las apps con LLM.',
    layer: 'production',
    kind: 'concept',
    level: 2,
    tags: ['inyección indirecta', 'tool poisoning', 'exfiltración'],
    prerequisites: ['tool-calling', 'context-window'],
    relations: [],
    labId: 'injection',
  },
  {
    id: 'guardrails',
    title: 'Guardrails',
    short: 'Validaciones de entrada y salida (clasificadores, reglas, esquemas): mitigan riesgos, no los eliminan.',
    layer: 'production',
    kind: 'technique',
    level: 2,
    tags: ['NeMo Guardrails', 'Llama Guard', 'moderación', 'validación'],
    prerequisites: ['prompt-injection'],
    relations: [{ to: 'prompt-injection', type: 'mitigates' }],
  },
  {
    id: 'owasp-llm-top10',
    title: 'OWASP Top 10 para LLMs',
    short: 'El catálogo de riesgos de referencia: inyección, fuga de datos, agencia excesiva, consumo sin límite…',
    layer: 'production',
    kind: 'concept',
    level: 2,
    tags: ['OWASP', 'seguridad', 'excessive agency'],
    prerequisites: ['prompt-injection'],
    relations: [{ to: 'guardrails', type: 'uses' }],
  },
  {
    id: 'cost-latency-optimization',
    title: 'Optimización de coste y latencia',
    short: 'Caching, routing entre modelos, batching y streaming: pagar menos y responder antes sin perder calidad.',
    layer: 'production',
    kind: 'technique',
    level: 2,
    tags: ['caching', 'routing', 'batch API', 'cascadas'],
    prerequisites: ['latency-cost-metrics', 'model-selection'],
    relations: [
      { to: 'inference-optimizations', type: 'uses' },
      { to: 'observability', type: 'uses' },
    ],
  },
]
