import type { ConceptMeta } from '../schema'

export const tools: ConceptMeta[] = [
  {
    id: 'tool-calling',
    title: 'Tool calling',
    short: 'El modelo pide ejecutar una función con argumentos JSON; tu código la ejecuta y le devuelve el resultado.',
    layer: 'tools',
    kind: 'technique',
    level: 1,
    tags: ['function calling', 'tool_use', 'JSON Schema'],
    prerequisites: ['llm-apis', 'structured-outputs'],
    relations: [{ to: 'agent-loop', type: 'enables' }],
    labId: 'tool-calling',
  },
  {
    id: 'mcp',
    title: 'Model Context Protocol (MCP)',
    short: 'Protocolo abierto (JSON-RPC) para que cualquier app host conecte herramientas, recursos y prompts de servidores.',
    layer: 'tools',
    kind: 'protocol',
    level: 2,
    tags: ['JSON-RPC', 'stdio', 'Streamable HTTP', 'tools', 'resources'],
    prerequisites: ['tool-calling'],
    relations: [
      { to: 'tool-calling', type: 'uses' },
      { to: 'a2a', type: 'alternative', note: 'MCP conecta herramientas; A2A conecta agentes' },
    ],
    labId: 'mcp',
  },
  {
    id: 'a2a',
    title: 'Agent2Agent (A2A)',
    short: 'Protocolo para que agentes de distintos proveedores se descubran y deleguen tareas entre sí.',
    layer: 'tools',
    kind: 'protocol',
    level: 3,
    tags: ['agent card', 'interoperabilidad', 'tareas'],
    prerequisites: ['mcp', 'multi-agent'],
    relations: [{ to: 'multi-agent', type: 'enables' }],
  },
  {
    id: 'computer-use',
    title: 'Computer use',
    short: 'Agentes que ven la pantalla y usan ratón y teclado: la herramienta universal, y la más frágil.',
    layer: 'tools',
    kind: 'technique',
    level: 2,
    tags: ['navegador', 'capturas', 'acciones GUI'],
    prerequisites: ['tool-calling', 'multimodality'],
    relations: [{ to: 'agent-loop', type: 'uses' }],
  },
  {
    id: 'code-sandboxes',
    title: 'Sandboxes de ejecución',
    short: 'Entornos aislados donde un agente puede ejecutar código sin poner en riesgo tu sistema.',
    layer: 'tools',
    kind: 'tool',
    level: 2,
    tags: ['aislamiento', 'contenedores', 'code interpreter'],
    prerequisites: ['tool-calling'],
    relations: [
      { to: 'coding-agents', type: 'enables' },
      { to: 'prompt-injection', type: 'mitigates', note: 'limita el daño posible' },
    ],
  },
]
