import type { GlossaryTerm } from './schema'

/* Short, precise definitions. Used by <Term> tooltips in theory pages,
   the glossary page and the command palette. */

export const GLOSSARY: GlossaryTerm[] = [
  { id: 'token', term: 'Token', definition: 'Unidad mínima de texto que procesa un modelo: una palabra, un trozo de palabra, un signo o un byte. Los modelos cuentan, cobran y limitan en tokens.', concept: 'tokenization' },
  { id: 'bpe', term: 'BPE (Byte-Pair Encoding)', definition: 'Algoritmo que construye el vocabulario fusionando repetidamente el par de símbolos más frecuente del corpus de entrenamiento.', concept: 'tokenization' },
  { id: 'vocabulary', term: 'Vocabulario', definition: 'Conjunto fijo de tokens que conoce un modelo (típicamente 32k–260k). Cada token tiene un id entero.', concept: 'tokenization' },
  { id: 'embedding', term: 'Embedding', definition: 'Vector denso de números reales que representa un token, frase o documento, de forma que significados parecidos quedan cerca.', concept: 'embeddings' },
  { id: 'cosine-similarity', term: 'Similitud coseno', definition: 'Coseno del ángulo entre dos vectores: 1 = misma dirección, 0 = ortogonales. La métrica más usada para comparar embeddings.', concept: 'embeddings' },
  { id: 'transformer', term: 'Transformer', definition: 'Arquitectura de red neuronal basada en bloques de atención + capas feed-forward. Base de todos los LLM actuales.', concept: 'attention' },
  { id: 'self-attention', term: 'Self-attention', definition: 'Mecanismo por el que cada token calcula una media ponderada de los vectores de otros tokens, con pesos según su relevancia (Q·K).', concept: 'attention' },
  { id: 'qkv', term: 'Query, Key, Value', definition: 'Tres proyecciones de cada token: la query pregunta, las keys responden "cuánto encajo" y los values son la información que se mezcla.', concept: 'attention' },
  { id: 'attention-head', term: 'Cabeza de atención', definition: 'Una de varias atenciones en paralelo dentro de una capa; cada una aprende a fijarse en relaciones distintas.', concept: 'attention' },
  { id: 'causal-mask', term: 'Máscara causal', definition: 'Restricción que impide que un token atienda a tokens posteriores: por eso un LLM solo puede mirar hacia atrás.', concept: 'attention' },
  { id: 'rope', term: 'RoPE', definition: 'Rotary Position Embedding: codifica la posición rotando las queries y keys, de modo que la atención depende de la distancia relativa.', concept: 'attention' },
  { id: 'gqa', term: 'GQA (Grouped-Query Attention)', definition: 'Varias cabezas de query comparten las mismas keys/values. Reduce mucho el tamaño del KV cache con poca pérdida de calidad.', concept: 'attention' },
  { id: 'parameters', term: 'Parámetros (pesos)', definition: 'Los números aprendidos del modelo. "8B" significa 8.000 millones de parámetros; en FP16 ocupan 2 bytes cada uno.', concept: 'training' },
  { id: 'logits', term: 'Logits', definition: 'Puntuaciones sin normalizar que el modelo asigna a cada token del vocabulario antes del softmax.', concept: 'next-token' },
  { id: 'softmax', term: 'Softmax', definition: 'Función que convierte logits en probabilidades positivas que suman 1: p_i = e^(z_i) / Σ e^(z_j).', concept: 'next-token' },
  { id: 'autoregressive', term: 'Autorregresivo', definition: 'Que genera un token cada vez y lo añade a la entrada para generar el siguiente.', concept: 'next-token' },
  { id: 'temperature', term: 'Temperature', definition: 'Divide los logits antes del softmax. <1 concentra la probabilidad en los tokens favoritos; >1 la reparte. 0 equivale a greedy.', concept: 'sampling' },
  { id: 'top-k', term: 'Top-k', definition: 'Muestrear solo entre los k tokens más probables.', concept: 'sampling' },
  { id: 'top-p', term: 'Top-p (nucleus)', definition: 'Muestrear solo entre el conjunto mínimo de tokens cuya probabilidad acumulada supera p.', concept: 'sampling' },
  { id: 'min-p', term: 'Min-p', definition: 'Descartar tokens cuya probabilidad sea menor que min_p × la probabilidad del token más probable. Se adapta a la confianza del modelo.', concept: 'sampling' },
  { id: 'greedy', term: 'Greedy decoding', definition: 'Elegir siempre el token más probable. Determinista, pero tiende a repetirse en textos largos.', concept: 'sampling' },
  { id: 'context-window', term: 'Ventana de contexto', definition: 'Número máximo de tokens (entrada + salida) que el modelo puede procesar en una llamada.', concept: 'context-window' },
  { id: 'kv-cache', term: 'KV cache', definition: 'Memoria donde se guardan las keys y values ya calculadas de los tokens previos para no recalcularlas en cada paso de generación.', concept: 'context-window' },
  { id: 'prefill', term: 'Prefill', definition: 'Fase inicial en la que el modelo procesa todo el prompt en paralelo y llena el KV cache. Determina el TTFT.', concept: 'context-window' },
  { id: 'decode', term: 'Decode', definition: 'Fase en la que se genera un token por paso. Limitada por el ancho de banda de memoria, no por el cómputo.', concept: 'context-window' },
  { id: 'ttft', term: 'TTFT', definition: 'Time To First Token: tiempo hasta que llega el primer token de la respuesta.', concept: 'latency-cost-metrics' },
  { id: 'pretraining', term: 'Pre-training', definition: 'Entrenamiento inicial prediciendo el siguiente token sobre billones de tokens de texto. Produce el modelo base.', concept: 'training' },
  { id: 'base-model', term: 'Modelo base', definition: 'Modelo tras el pre-training: completa texto, pero no sigue instrucciones ni mantiene un rol de asistente.', concept: 'training' },
  { id: 'sft', term: 'SFT', definition: 'Supervised Fine-Tuning: entrenar con pares instrucción → respuesta ideal para enseñar formato y comportamiento.', concept: 'training' },
  { id: 'rlhf', term: 'RLHF', definition: 'Reinforcement Learning from Human Feedback: optimizar el modelo contra un modelo de recompensa entrenado con preferencias humanas.', concept: 'training' },
  { id: 'dpo', term: 'DPO', definition: 'Direct Preference Optimization: aprende de pares (respuesta preferida, rechazada) sin entrenar un modelo de recompensa aparte.', concept: 'training' },
  { id: 'reward-model', term: 'Modelo de recompensa', definition: 'Modelo que puntúa respuestas imitando preferencias humanas; se usa como señal en RLHF.', concept: 'training' },
  { id: 'cot', term: 'Chain of thought', definition: 'Razonamiento intermedio paso a paso que el modelo genera antes de la respuesta final.', concept: 'reasoning-models' },
  { id: 'test-time-compute', term: 'Test-time compute', definition: 'Cómputo gastado durante la inferencia (tokens de razonamiento, múltiples intentos) para mejorar la respuesta.', concept: 'reasoning-models' },
  { id: 'moe', term: 'MoE', definition: 'Mixture of Experts: capas con muchos sub-redes "expertas" de las que solo unas pocas se activan por token.', concept: 'mixture-of-experts' },
  { id: 'router', term: 'Router (gating)', definition: 'Pequeña red que, para cada token, elige qué expertos de una capa MoE lo procesan.', concept: 'mixture-of-experts' },
  { id: 'hallucination', term: 'Alucinación', definition: 'Salida fluida y segura de sí misma pero falsa o no respaldada por las fuentes. Consecuencia de optimizar plausibilidad, no verdad.' },
  { id: 'quantization', term: 'Cuantización', definition: 'Representar los pesos con menos bits (p. ej. 4 en vez de 16) para reducir memoria y acelerar, perdiendo algo de precisión.', concept: 'quantization' },
  { id: 'gguf', term: 'GGUF', definition: 'Formato de fichero de llama.cpp que empaqueta pesos (a menudo cuantizados), tokenizador y metadatos en un solo archivo.', concept: 'weight-formats' },
  { id: 'rag', term: 'RAG', definition: 'Retrieval-Augmented Generation: recuperar información relevante y añadirla al prompt para que el modelo responda con ella.', concept: 'rag' },
  { id: 'chunk', term: 'Chunk', definition: 'Fragmento de un documento que se indexa y recupera como unidad en un sistema RAG.', concept: 'chunking' },
  { id: 'ann', term: 'ANN', definition: 'Approximate Nearest Neighbors: búsqueda de vecinos cercanos que sacrifica un poco de exactitud para ser órdenes de magnitud más rápida.', concept: 'ann-indexes' },
  { id: 'tool-calling', term: 'Tool calling', definition: 'Capacidad del modelo de devolver una petición estructurada (nombre + argumentos JSON) para que la aplicación ejecute una función.', concept: 'tool-calling' },
  { id: 'mcp', term: 'MCP', definition: 'Model Context Protocol: protocolo abierto basado en JSON-RPC para conectar aplicaciones con servidores que exponen herramientas, recursos y prompts.', concept: 'mcp' },
  { id: 'agent', term: 'Agente', definition: 'Sistema en el que un LLM decide dinámicamente qué acciones tomar, en bucle, hasta cumplir un objetivo.', concept: 'agent-loop' },
  { id: 'lora', term: 'LoRA', definition: 'Low-Rank Adaptation: fine-tuning que entrena solo dos matrices pequeñas por capa en lugar de todos los pesos.', concept: 'fine-tuning' },
  { id: 'guardrail', term: 'Guardrail', definition: 'Control automático sobre entradas o salidas de un LLM (clasificador, regla, validador) para reducir riesgos.', concept: 'guardrails' },
  { id: 'eval', term: 'Eval', definition: 'Evaluación sistemática de un sistema con LLM sobre un conjunto de casos, con métricas y umbrales.', concept: 'evals' },
  { id: 'prompt-injection', term: 'Prompt injection', definition: 'Ataque en el que texto controlado por un tercero contiene instrucciones que el modelo acaba obedeciendo.', concept: 'prompt-injection' },
  { id: 'perplexity', term: 'Perplejidad', definition: 'Medida de lo "sorprendido" que está un modelo por un texto: exp de la pérdida media por token. Menor es mejor; solo comparable con el mismo tokenizador.', concept: 'next-token' },
  { id: 'flash-attention', term: 'FlashAttention', definition: 'Implementación de la atención que evita materializar la matriz completa en memoria lenta. Mismo resultado, mucho más rápida.', concept: 'inference-optimizations' },
]

export const GLOSSARY_BY_ID: ReadonlyMap<string, GlossaryTerm> = new Map(
  GLOSSARY.map((g) => [g.id, g]),
)
