import type { Surface } from './types'

/* Attack surfaces of an LLM application or agent, grouped by trust zone.
   The attacks that apply to each surface are derived from ATTACKS. */

export const SURFACES: Surface[] = [
  // ── Entradas no confiables ─────────────────────────────────────────────
  {
    id: 's-user-input',
    n: 1,
    zone: 'untrusted',
    title: 'Entrada del usuario',
    short: 'Mensajes, formularios, ficheros y voz que envía quien usa el sistema.',
    includes: ['Chat y formularios', 'Ficheros subidos', 'Voz transcrita', 'Parámetros de API de tu propio servicio'],
    exposure: 'Cualquier usuario, incluido uno malicioso, controla este texto por completo y puede iterar hasta encontrar un fallo.',
    controls: [
      { kind: 'prevent', text: 'Autenticación, límites de longitud y de frecuencia, dominio acotado por producto.' },
      { kind: 'prevent', text: 'Clasificador de entrada (jailbreak, abuso, temas fuera de alcance) y normalización Unicode.' },
      { kind: 'detect', text: 'Registro de intentos bloqueados y detección de patrones repetidos por usuario.' },
      { kind: 'respond', text: 'Bloqueo o limitación de cuentas abusivas; revisión de conversaciones marcadas.' },
    ],
    review: [
      '¿Qué puede conseguir un usuario malicioso que consiga que el modelo haga cualquier cosa? Ese es el impacto real.',
      '¿Hay decisiones de autorización que dependan de lo que el modelo «decida»?',
      '¿Qué longitud y qué tipos de fichero se aceptan, y por qué?',
    ],
    concepts: ['prompt-injection', 'guardrails'],
    cases: ['support-rag'],
  },
  {
    id: 's-external-content',
    n: 2,
    zone: 'untrusted',
    title: 'Contenido externo en el contexto',
    short: 'Todo lo que el sistema lee por su cuenta: documentos, webs, emails, resultados de herramientas.',
    includes: ['Fragmentos recuperados por RAG', 'Páginas web y resultados de búsqueda', 'Emails, tickets, issues, comentarios', 'Respuestas de APIs y de otras IAs'],
    exposure: 'Lo escriben terceros que no son usuarios del sistema, y llega al mismo contexto que tus instrucciones. Es la vía de la inyección indirecta.',
    controls: [
      { kind: 'prevent', text: 'Marcar el contenido como datos (delimitadores, datamarking) y minimizar lo que entra en el contexto.' },
      { kind: 'prevent', text: 'Arquitecturas donde el contenido no confiable no pueda disparar acciones (dual LLM, plan-then-execute).' },
      { kind: 'detect', text: 'Detectores de inyección sobre el contenido recuperado y alertas por instrucciones dirigidas a IAs.' },
      { kind: 'respond', text: 'Poder identificar qué documento o página provocó una acción y retirarlo de las fuentes.' },
    ],
    review: [
      'Enumera todas las fuentes de texto que llegan al modelo sin que las escriba el usuario. ¿Quién puede escribir en cada una?',
      '¿Coinciden en el mismo contexto contenido no confiable, datos privados y una forma de comunicar hacia fuera?',
      '¿Se conserva la procedencia de cada fragmento hasta la traza?',
    ],
    concepts: ['prompt-injection', 'rag'],
    cases: ['mcp-copilot', 'coding-agent', 'deep-research'],
  },
  {
    id: 's-multimodal',
    n: 3,
    zone: 'untrusted',
    title: 'Entradas multimodales',
    short: 'Imágenes, capturas, PDFs escaneados y audio que el modelo interpreta.',
    includes: ['Capturas de pantalla (computer use)', 'Imágenes subidas', 'PDFs escaneados', 'Audio'],
    exposure: 'Pueden contener texto que el modelo lee y las personas no ven, y los filtros de texto no los inspeccionan.',
    controls: [
      { kind: 'prevent', text: 'Tratar el contenido visual como no confiable; extraer texto (OCR) y aplicar los mismos filtros.' },
      { kind: 'prevent', text: 'Limitar las acciones que dependen de lo que el modelo «ve» sin confirmación.' },
      { kind: 'detect', text: 'Conservar las imágenes que precedieron a acciones relevantes para poder auditarlas.' },
    ],
    review: ['¿Qué acciones puede desencadenar el contenido de una imagen?', '¿Se registra qué vio el modelo antes de actuar?'],
    concepts: ['multimodality', 'computer-use'],
    cases: [],
  },
  // ── Aplicación y orquestación ───────────────────────────────────────────
  {
    id: 's-system-prompt',
    n: 4,
    zone: 'app',
    title: 'System prompt y configuración',
    short: 'Instrucciones del sistema, definiciones de herramientas y parámetros del modelo.',
    includes: ['System prompt', 'Ejemplos few-shot', 'Definiciones de herramientas', 'Parámetros (modelo, esfuerzo, límites)'],
    exposure: 'Se puede extraer casi siempre, y su texto define el comportamiento. Un cambio no revisado es un cambio de seguridad.',
    controls: [
      { kind: 'prevent', text: 'Sin secretos, credenciales ni reglas de autorización en el prompt; asumir que es público.' },
      { kind: 'prevent', text: 'Versionado, revisión y despliegue controlado de prompts, como código.' },
      { kind: 'detect', text: 'Evals de regresión y de seguridad en cada cambio de prompt o de modelo.' },
    ],
    review: ['Si el system prompt se publicara mañana, ¿qué problema habría?', '¿Quién puede cambiar los prompts en producción y queda registro?'],
    concepts: ['prompt-engineering', 'owasp-llm-top10'],
    cases: [],
  },
  {
    id: 's-orchestrator',
    n: 5,
    zone: 'app',
    title: 'Bucle del agente y orquestación',
    short: 'El código que decide qué hace el modelo después de cada paso.',
    includes: ['Bucle ReAct o grafo con estado', 'Planificador y ejecutor', 'Límites de pasos y presupuesto', 'Checkpoints'],
    exposure: 'Si el flujo de control lo decide el modelo tras leer contenido no confiable, el atacante puede redirigirlo.',
    controls: [
      { kind: 'prevent', text: 'Flujo de control fijado antes de leer datos no confiables cuando sea posible (plan-then-execute).' },
      { kind: 'prevent', text: 'Límites de pasos, tiempo, tokens y coste por tarea; política explícita de acciones permitidas.' },
      { kind: 'detect', text: 'Trazas completas de cada decisión y alertas por bucles o desviaciones del plan.' },
      { kind: 'respond', text: 'Kill switch por agente y por usuario; posibilidad de revertir acciones (checkpoints).' },
    ],
    review: ['¿Qué impide que el agente haga algo no previsto en el plan?', '¿Hay un límite duro de pasos y coste? ¿Qué pasa al alcanzarlo?'],
    concepts: ['agent-loop', 'stateful-graphs', 'workflow-patterns'],
    cases: ['coding-agent', 'deep-research'],
  },
  {
    id: 's-memory',
    n: 6,
    zone: 'app',
    title: 'Memoria y estado persistente',
    short: 'Lo que el agente recuerda entre sesiones: preferencias, hechos, historial.',
    includes: ['Memoria a largo plazo', 'Perfiles de usuario', 'Historial de conversaciones', 'Estado de checkpoints'],
    exposure: 'Lo que entra en memoria afecta a todas las sesiones futuras; una inyección puede volverse permanente.',
    controls: [
      { kind: 'prevent', text: 'Escrituras en memoria validadas, con origen y fecha; nunca instrucciones, solo hechos.' },
      { kind: 'prevent', text: 'Aislamiento estricto de la memoria por usuario y por tenant.' },
      { kind: 'detect', text: 'Memoria visible y editable por el usuario; revisión de entradas anómalas.' },
      { kind: 'respond', text: 'Borrado selectivo y total (también para cumplir el derecho de supresión).' },
    ],
    review: ['¿Quién o qué puede escribir en la memoria? ¿Se puede ver y borrar?', '¿Se puede mezclar la memoria de dos usuarios en algún camino?'],
    concepts: ['agent-memory'],
    cases: [],
  },
  {
    id: 's-multi-agent',
    n: 7,
    zone: 'app',
    title: 'Comunicación entre agentes',
    short: 'Mensajes entre orquestador y subagentes, o entre agentes de distintas organizaciones (A2A).',
    includes: ['Supervisor y subagentes', 'Handoffs', 'Protocolo A2A y Agent Cards', 'Colas y memorias compartidas'],
    exposure: 'Un agente comprometido o que lee contenido malicioso puede transmitir instrucciones a otro con más privilegios.',
    controls: [
      { kind: 'prevent', text: 'Tratar la salida de otros agentes como no confiable; esquemas estrictos para sus respuestas.' },
      { kind: 'prevent', text: 'Autenticación mutua entre agentes, Agent Cards firmadas y privilegios distintos por agente.' },
      { kind: 'detect', text: 'Trazas que enlacen toda la cadena de delegación.' },
    ],
    review: ['¿Algún agente con acceso a datos sensibles recibe texto de un agente que lee contenido externo?', '¿Cómo se autentica un agente externo?'],
    concepts: ['multi-agent', 'a2a'],
    cases: ['deep-research'],
  },
  {
    id: 's-hitl',
    n: 8,
    zone: 'app',
    title: 'Aprobaciones humanas e interfaz',
    short: 'Confirmaciones, revisiones y lo que la interfaz muestra al usuario.',
    includes: ['Diálogos de confirmación', 'Revisión de diffs y borradores', 'Renderizado de respuestas', 'Notificaciones'],
    exposure: 'Si la persona aprueba por costumbre o ve una descripción distinta de lo que se ejecuta, el control no existe.',
    controls: [
      { kind: 'prevent', text: 'Confirmaciones solo para lo que importa, con los parámetros reales generados por el sistema (no por el modelo).' },
      { kind: 'prevent', text: 'Interfaz sin renderizado de recursos remotos arbitrarios y con CSP estricta.' },
      { kind: 'detect', text: 'Medir tasas de aprobación y tiempo de revisión para detectar fatiga.' },
    ],
    review: ['¿La confirmación muestra destino, importe o diff exactos?', '¿Cuántas confirmaciones ve un usuario al día?'],
    concepts: ['guardrails', 'stateful-graphs'],
    cases: ['invoice-automation', 'mcp-copilot', 'coding-agent'],
  },
  // ── Modelo ──────────────────────────────────────────────────────────────
  {
    id: 's-model-behavior',
    n: 9,
    zone: 'model',
    title: 'Comportamiento del modelo',
    short: 'Lo que el modelo hace ante entradas adversariales, ambiguas o fuera de dominio.',
    includes: ['Entrenamiento de seguridad', 'Tendencia a alucinar', 'Seguimiento de instrucciones', 'Sesgos'],
    exposure: 'Es probabilístico: ninguna defensa basada en el propio modelo es completa. No es una frontera de seguridad.',
    controls: [
      { kind: 'prevent', text: 'Elegir modelos con buena resistencia medida a inyección y jailbreaks para tu caso.' },
      { kind: 'prevent', text: 'Guardrails de entrada y salida como capas adicionales, nunca como la única.' },
      { kind: 'detect', text: 'Red teaming continuo y evals de seguridad en cada cambio de modelo.' },
    ],
    review: ['¿Qué pasa si el modelo obedece a un atacante? Si la respuesta es «nada grave», el diseño es correcto.', '¿Se reevalúa la seguridad al cambiar de modelo o de versión?'],
    concepts: ['training', 'guardrails'],
    cases: [],
  },
  {
    id: 's-model-api',
    n: 10,
    zone: 'model',
    title: 'API del modelo y proveedor',
    short: 'El servicio (o el despliegue propio) que ejecuta el modelo.',
    includes: ['Proveedor de API', 'Retención de datos y residencia', 'Logprobs y parámetros expuestos', 'Modelos propios servidos por API'],
    exposure: 'Tus datos salen de tu perímetro; tu API de modelo propia puede ser abusada o clonada.',
    controls: [
      { kind: 'prevent', text: 'Contratos de tratamiento de datos, retención mínima, región y opciones de no entrenamiento.' },
      { kind: 'prevent', text: 'Límites por cliente, autenticación fuerte y no exponer logprobs sin necesidad.' },
      { kind: 'detect', text: 'Monitorizar patrones de consultas anómalos (extracción, scraping).' },
    ],
    review: ['¿Dónde se procesan y cuánto tiempo se guardan los datos que enviamos?', '¿Qué pasa si el proveedor tiene una caída o un incidente?'],
    concepts: ['llm-apis', 'open-vs-closed'],
    cases: [],
  },
  // ── Herramientas y acción ───────────────────────────────────────────────
  {
    id: 's-tools',
    n: 11,
    zone: 'action',
    title: 'Herramientas y function calling',
    short: 'Las funciones que el modelo puede pedir que se ejecuten.',
    includes: ['Definiciones y esquemas', 'Implementación de cada herramienta', 'Credenciales que usan', 'Resultados que devuelven'],
    exposure: 'Convierten texto en acciones. Cada herramienta amplía lo que un atacante puede conseguir.',
    controls: [
      { kind: 'prevent', text: 'Herramientas específicas, con parámetros validados por esquema y autorización con la identidad del usuario.' },
      { kind: 'prevent', text: 'Allowlists de destinos en las que comunican hacia fuera; confirmación en las irreversibles.' },
      { kind: 'detect', text: 'Registrar cada llamada con parámetros, identidad y resultado.' },
      { kind: 'respond', text: 'Poder desactivar una herramienta al instante y revertir sus efectos.' },
    ],
    review: ['Para cada herramienta: ¿qué es lo peor que puede hacer con parámetros elegidos por un atacante?', '¿Con qué identidad y permisos se ejecuta?'],
    concepts: ['tool-calling', 'structured-outputs'],
    cases: ['coding-agent', 'invoice-automation', 'text-to-sql'],
  },
  {
    id: 's-mcp',
    n: 12,
    zone: 'action',
    title: 'Servidores MCP y conectores',
    short: 'Servidores locales o remotos que exponen herramientas, recursos y prompts.',
    includes: ['Servidores locales (stdio) y remotos (Streamable HTTP)', 'Descripciones de herramientas', 'Flujos OAuth', 'Clientes y proxies MCP'],
    exposure: 'Cada servidor ejecuta código con tus permisos o actúa con tus tokens, y su texto entra en el contexto del modelo.',
    controls: [
      { kind: 'prevent', text: 'Solo servidores oficiales o revisados, versiones fijadas, sandbox y consentimiento explícito al instalar.' },
      { kind: 'prevent', text: 'OAuth con scopes mínimos y progresivos, sin token passthrough; validar Origin y URLs.' },
      { kind: 'detect', text: 'Alertas cuando cambian las definiciones de herramientas (rug pull).' },
      { kind: 'respond', text: 'Inventario de servidores por usuario y revocación centralizada de tokens.' },
    ],
    review: ['¿Qué servidores MCP hay instalados, de dónde vienen y quién los aprobó?', '¿Qué scopes tiene cada token? ¿Dónde se guardan?', '¿Se detecta un cambio en tools/list?'],
    concepts: ['mcp'],
    cases: ['mcp-copilot', 'coding-agent'],
  },
  {
    id: 's-code-exec',
    n: 13,
    zone: 'action',
    title: 'Ejecución de código',
    short: 'Sandboxes, intérpretes y terminales donde el agente ejecuta código.',
    includes: ['Code interpreter', 'Terminales de agentes de código', 'Contenedores y microVMs', 'Instalación de dependencias'],
    exposure: 'Es ejecución de código arbitrario por diseño: todo depende del aislamiento.',
    controls: [
      { kind: 'prevent', text: 'MicroVM o sandbox sin privilegios, sin credenciales, efímero, con egress denegado por defecto.' },
      { kind: 'prevent', text: 'Límites de CPU, memoria, disco y tiempo; sin acceso a metadatos de la nube ni redes internas.' },
      { kind: 'detect', text: 'Registro de comandos y conexiones de red intentadas.' },
    ],
    review: ['¿Qué ve el código ejecutado: ficheros, variables de entorno, red, sockets?', '¿Puede instalar paquetes? ¿De dónde?'],
    concepts: ['code-sandboxes', 'coding-agents'],
    cases: ['coding-agent', 'text-to-sql'],
  },
  {
    id: 's-browser',
    n: 14,
    zone: 'action',
    title: 'Navegador y computer use',
    short: 'Agentes que navegan, rellenan formularios o controlan un escritorio.',
    includes: ['Navegador controlado (Playwright, CDP)', 'Sesiones iniciadas y cookies', 'Autocompletado', 'Descargas'],
    exposure: 'Todo lo que muestra cualquier web entra en el contexto, y el navegador puede tener tus sesiones.',
    controls: [
      { kind: 'prevent', text: 'Navegador aislado y efímero, sin sesiones personales ni gestor de contraseñas.' },
      { kind: 'prevent', text: 'Dominios permitidos por tarea; confirmación antes de pagos, envíos y datos personales.' },
      { kind: 'detect', text: 'Grabación de sesiones y capturas de cada acción.' },
    ],
    review: ['¿En qué webs tiene sesión el navegador del agente?', '¿Qué acciones puede completar sin que nadie las confirme?'],
    concepts: ['computer-use'],
    cases: ['deep-research'],
  },
  {
    id: 's-output',
    n: 15,
    zone: 'action',
    title: 'Salida hacia otros sistemas',
    short: 'Dónde acaba lo que genera el modelo: interfaz, bases de datos, shells, APIs, ficheros.',
    includes: ['Markdown y HTML renderizado', 'SQL, comandos y código generados', 'Rutas y URLs', 'JSON hacia otras APIs'],
    exposure: 'La salida del modelo es entrada controlable por el atacante para el siguiente sistema.',
    controls: [
      { kind: 'prevent', text: 'Validación por esquema, consultas parametrizadas, codificación de salida y nada de eval().' },
      { kind: 'prevent', text: 'Sin imágenes remotas en respuestas (o solo de dominios permitidos) y CSP estricta.' },
      { kind: 'detect', text: 'Detectores de datos sensibles y de URLs sospechosas en la salida.' },
    ],
    review: ['¿Qué intérpretes consumen la salida del modelo? ¿Cómo se valida en cada uno?', '¿La interfaz puede cargar recursos externos a partir de una respuesta?'],
    concepts: ['structured-outputs', 'owasp-llm-top10'],
    cases: ['text-to-sql', 'support-rag'],
  },
  // ── Datos e identidad ───────────────────────────────────────────────────
  {
    id: 's-rag',
    n: 16,
    zone: 'data',
    title: 'Ingesta, índice vectorial y RAG',
    short: 'Fuentes, pipeline de ingesta, base vectorial y recuperación.',
    includes: ['Conectores a fuentes (wikis, drives, tickets)', 'Parsing y chunking', 'Base vectorial y embeddings', 'Filtros de permisos'],
    exposure: 'Quien escribe en una fuente escribe en el contexto del modelo; el índice concentra información de todos.',
    controls: [
      { kind: 'prevent', text: 'Permisos del usuario aplicados en la recuperación y aislamiento por tenant en la capa de datos.' },
      { kind: 'prevent', text: 'Control de qué fuentes se indexan y quién puede escribir en ellas; procedencia en metadatos.' },
      { kind: 'detect', text: 'Alertas por documentos nuevos o cambiados que se recuperan de forma anómala.' },
      { kind: 'respond', text: 'Reindexado y borrado efectivo (también de embeddings y cachés).' },
    ],
    review: ['¿La búsqueda filtra por los permisos de quien pregunta? ¿En todos los caminos?', '¿Quién puede escribir en las fuentes indexadas?', '¿Cómo se borra un documento del índice?'],
    concepts: ['rag', 'vector-databases', 'embedding-models'],
    cases: ['support-rag'],
  },
  {
    id: 's-secrets',
    n: 17,
    zone: 'data',
    title: 'Identidad, credenciales y secretos',
    short: 'Claves de API, tokens OAuth, cuentas de servicio y la identidad con la que actúa el agente.',
    includes: ['Claves de proveedores de modelos', 'Tokens OAuth de conectores', 'Cuentas de servicio', 'Identidad del usuario final'],
    exposure: 'El agente necesita credenciales para actuar; si son amplias o están a su alcance, un atacante las usa a través de él.',
    controls: [
      { kind: 'prevent', text: 'Actuar con la identidad del usuario, tokens de corta duración y scopes mínimos.' },
      { kind: 'prevent', text: 'Secretos en un gestor, fuera del prompt, del cliente y del entorno del sandbox.' },
      { kind: 'detect', text: 'Detección de secretos en prompts, salidas, repos y trazas; alertas de uso anómalo.' },
      { kind: 'respond', text: 'Rotación y revocación rápidas.' },
    ],
    review: ['¿Con qué identidad actúa el agente en cada sistema?', '¿Hay alguna clave en el frontend, el prompt o variables de entorno legibles por el agente?'],
    concepts: ['mcp', 'guardrails'],
    cases: ['coding-agent', 'mcp-copilot'],
  },
  {
    id: 's-telemetry',
    n: 18,
    zone: 'data',
    title: 'Logs, trazas y datasets',
    short: 'Observabilidad, conversaciones guardadas y datos de evaluación.',
    includes: ['Trazas de prompts y respuestas', 'Herramientas de observabilidad de terceros', 'Datasets de evals', 'Feedback de usuarios'],
    exposure: 'Concentran todo lo que pasó por el sistema, con PII y secretos, a menudo con acceso amplio y retención larga.',
    controls: [
      { kind: 'prevent', text: 'Enmascarado de PII y secretos antes de registrar; retención limitada; acceso mínimo.' },
      { kind: 'prevent', text: 'Acuerdos de tratamiento con proveedores de observabilidad; autoalojar si hace falta.' },
      { kind: 'detect', text: 'Auditoría de accesos a trazas y datasets.' },
    ],
    review: ['¿Qué datos personales hay en las trazas y quién puede verlos?', '¿Cuánto tiempo se guardan y dónde?'],
    concepts: ['observability', 'evals'],
    cases: [],
  },
  // ── Plataforma y suministro ─────────────────────────────────────────────
  {
    id: 's-supply-chain',
    n: 19,
    zone: 'platform',
    title: 'Cadena de suministro',
    short: 'Modelos, datasets, librerías, servidores MCP y extensiones de terceros.',
    includes: ['Pesos descargados de hubs', 'Frameworks y SDKs', 'Servidores MCP y plugins', 'Plantillas de chat y tokenizadores'],
    exposure: 'Código y datos de terceros que se ejecutan o se cargan con tus privilegios.',
    controls: [
      { kind: 'prevent', text: 'Fuentes verificadas, formatos seguros (safetensors), versiones y hashes fijados, SBOM.' },
      { kind: 'prevent', text: 'Registros internos de paquetes y modelos; sin instalar dependencias sin aprobación.' },
      { kind: 'detect', text: 'Escaneo de dependencias y de artefactos de modelo; seguimiento de avisos de seguridad.' },
    ],
    review: ['¿Hay inventario de modelos, datasets, paquetes y servidores en uso?', '¿Algún modelo se carga con pickle o trust_remote_code?'],
    concepts: ['hugging-face', 'weight-formats'],
    cases: ['coding-agent'],
  },
  {
    id: 's-training',
    n: 20,
    zone: 'platform',
    title: 'Entrenamiento y fine-tuning',
    short: 'Datos y procesos con los que se ajustan tus modelos.',
    includes: ['Datasets de fine-tuning', 'Datos de preferencias', 'Pipelines de entrenamiento', 'Modelos ajustados de terceros'],
    exposure: 'Lo que entra en el entrenamiento puede quedar memorizado o introducir comportamientos ocultos.',
    controls: [
      { kind: 'prevent', text: 'Procedencia y revisión de datos; anonimización y deduplicación.' },
      { kind: 'detect', text: 'Evals de seguridad y de extracción antes de desplegar cada modelo ajustado.' },
    ],
    review: ['¿De dónde vienen los datos de fine-tuning y quién pudo modificarlos?', '¿Se ha probado si el modelo reproduce datos sensibles?'],
    concepts: ['fine-tuning', 'training'],
    cases: [],
  },
  {
    id: 's-infra',
    n: 21,
    zone: 'platform',
    title: 'Infraestructura de inferencia',
    short: 'Servidores, GPUs, cachés y redes donde se ejecutan modelos y agentes.',
    includes: ['Servidores de inferencia (vLLM, Ollama…)', 'GPUs compartidas', 'Cachés de prompts y KV', 'Endpoints internos'],
    exposure: 'Servicios de inferencia expuestos sin autenticación, recursos compartidos entre tenants y canales laterales.',
    controls: [
      { kind: 'prevent', text: 'Autenticación y red privada para endpoints de inferencia (Ollama y similares no traen auth por defecto).' },
      { kind: 'prevent', text: 'Aislamiento de cachés y GPUs por tenant; parches de drivers.' },
      { kind: 'detect', text: 'Monitorización de accesos y uso de recursos.' },
    ],
    review: ['¿Hay algún servidor de modelos accesible sin autenticación?', '¿Se comparten cachés o GPUs entre clientes?'],
    concepts: ['serving-engines', 'local-runtimes', 'inference-optimizations'],
    cases: [],
  },
  {
    id: 's-consumption',
    n: 22,
    zone: 'platform',
    title: 'Cuotas, coste y disponibilidad',
    short: 'Límites de uso, presupuestos y capacidad.',
    includes: ['Rate limits', 'Presupuestos por usuario y por agente', 'Gateway de modelos', 'Fallbacks'],
    exposure: 'El coste escala con los tokens: el abuso no tumba el servicio, vacía la cuenta.',
    controls: [
      { kind: 'prevent', text: 'Límites por usuario de peticiones, tokens y coste; max_tokens y límites de pasos en agentes.' },
      { kind: 'detect', text: 'Alertas de gasto y de consumo anómalo en el gateway.' },
      { kind: 'respond', text: 'Cortes automáticos por presupuesto y degradación a modelos más baratos.' },
    ],
    review: ['¿Cuál es el coste máximo que puede generar un usuario en una hora?', '¿Quién recibe la alerta si el gasto se dispara?'],
    concepts: ['cost-latency-optimization', 'latency-cost-metrics'],
    cases: ['deep-research'],
  },
]

export const SURFACE_BY_ID: ReadonlyMap<string, Surface> = new Map(SURFACES.map((s) => [s.id, s]))
